# Generated by Django 6.0.7 on 2026-07-07 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("raw_barcode", models.CharField(max_length=64, verbose_name="штрихкод")),
                (
                    "scanned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="время сканирования"),
                ),
                ("is_duplicate", models.BooleanField(default=False, verbose_name="дубликат")),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пусто, если штрихкод ещё не встречался в синхронизированном каталоге товаров.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_events",
                        to="integrations.product",
                        verbose_name="товар",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_events",
                        to="organizations.shop",
                        verbose_name="склад",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="работник",
                    ),
                ),
            ],
            options={
                "ordering": ["-scanned_at"],
                "indexes": [
                    models.Index(
                        fields=["shop", "scanned_at"], name="scanning_sc_shop_id_c95af1_idx"
                    ),
                    models.Index(
                        fields=["worker", "scanned_at"], name="scanning_sc_worker__44d1ba_idx"
                    ),
                ],
            },
        ),
    ]
