# Generated by Django 6.0.7 on 2026-07-07 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("scanning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scanevent",
            name="is_device_mismatch",
            field=models.BooleanField(
                default=False,
                help_text="Скан выполнен с устройства, закреплённого за другим работником.",
                verbose_name="несоответствие устройства",
            ),
        ),
        migrations.AddField(
            model_name="scanevent",
            name="unit_rate_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="ставка за единицу на момент сканирования",
            ),
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="идентификатор устройства"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="активно")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="создано")),
                (
                    "assigned_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="закреплённый работник",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="organizations.shop",
                        verbose_name="склад",
                    ),
                ),
            ],
            options={
                "ordering": ["identifier"],
            },
        ),
        migrations.AddField(
            model_name="scanevent",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scan_events",
                to="scanning.device",
                verbose_name="устройство",
            ),
        ),
    ]
