# Generated by Django 6.0.7 on 2026-07-07 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                help_text="Заполняется для менеджеров и работников; у владельца остаётся пустым.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff",
                to="organizations.shop",
                verbose_name="склад",
            ),
        ),
    ]
