# Generated by Django 6.0.7 on 2026-07-07 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="начало смены")),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="конец смены"),
                ),
                ("note", models.CharField(blank=True, max_length=255, verbose_name="примечание")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shifts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кем создано/изменено",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="organizations.shop",
                        verbose_name="склад",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="работник",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["shop", "started_at"], name="payroll_shi_shop_id_bd651b_idx"
                    ),
                    models.Index(
                        fields=["worker", "started_at"], name="payroll_shi_worker__2544d1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pay_type",
                    models.CharField(
                        choices=[
                            ("per_unit", "За единицу"),
                            ("hourly", "Почасовая"),
                            ("fixed_monthly", "Фиксированная (в месяц)"),
                        ],
                        max_length=20,
                        verbose_name="тип оплаты",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="ставка"),
                ),
                ("effective_from", models.DateField(verbose_name="действует с")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="создано")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tariffs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кем установлено",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="сотрудник",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "effective_from"], name="payroll_tar_user_id_dfcda8_idx"
                    )
                ],
            },
        ),
    ]
