# Generated by Django 6.0.7 on 2026-07-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "marketplace",
                    models.CharField(
                        choices=[("wildberries", "Wildberries"), ("uzum", "Uzum Market")],
                        max_length=20,
                        verbose_name="маркетплейс",
                    ),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="API-ключ")),
                ("is_active", models.BooleanField(default=True, verbose_name="активно")),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="последняя синхронизация"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="создано")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_connections",
                        to="organizations.organization",
                        verbose_name="организация",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(db_index=True, max_length=64, verbose_name="штрихкод"),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=128, verbose_name="внешний ID"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="название")),
                (
                    "rate_per_unit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="ставка за единицу"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="обновлено")),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="integrations.marketplaceconnection",
                        verbose_name="подключение",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="marketplaceconnection",
            constraint=models.UniqueConstraint(
                fields=("organization", "marketplace"), name="unique_connection_per_marketplace"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("connection", "barcode"), name="unique_barcode_per_connection"
            ),
        ),
    ]
